### ISSUE TITLE
[Feature Request] - API for Discord bots

### ISSUE THREAD

**Issue by basketballsmash-yt** [PidgeyL/TJADB#1]
## Before making a feature request
Check the roadmap in the readme file, and issues tagged "Feature Request" to see if the request or something similar already exists. If and issue exists, read the communication in that issue, and add comments or extra functionality there.

## Please describe the feature request below
**Is your feature request related to a problem? Please describe.**
People always ask for .tjas when they could find it themselves.

**Describe the solution you'd like**
Making an API that supports Discord bots so when the bot is called it searches the query given and gives the link to the chart.
**Describe alternatives you've considered**
When the word "find" and/or "tja" is mentioned the bot automatically gives the link to the website.
**Additional context**

**Comment by PidgeyL** [comment]
There is already an API built-in, that is currently not documented. I don't know if it "supports Discord Bots", since I haven't wroten any before, but if you're familiar with it, you could try it out. The full songlist can be found on /api/browse

**Comment by PidgeyL** [comment]
@basketballsmash-yt  Would this be enough to build a Discord bot?

**Comment by cnrad** [comment]
:+1:

**Comment by PidgeyL** [comment]
A prototype Discord Bot is running on the TJADB website. I will do further development on it as the over-all project grows
